/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spidership;

import java.awt.FlowLayout;
import java.awt.event.KeyEvent;

/**
 *
 * @author SummonerArthur
 */
public class Screen extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form Screen
     */
    public Screen() {
        initComponents();
        setLocationRelativeTo(null);
    }
boolean debugging=true;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        player = new javax.swing.JLabel();
        enm = new javax.swing.JLabel();
        enmAtk = new javax.swing.JLabel();
        projectile = new javax.swing.JLabel();
        enlifeBar = new javax.swing.JLabel();
        lifeBar = new javax.swing.JLabel();
        BG1 = new javax.swing.JLabel();
        BGSpace = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(640, 640));
        setMinimumSize(new java.awt.Dimension(640, 640));
        setPreferredSize(new java.awt.Dimension(642, 658));
        setResizable(false);
        setSize(new java.awt.Dimension(640, 640));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        player.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spidership/SPR/testnave.png"))); // NOI18N
        getContentPane().add(player, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));

        enm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spidership/SPR/enm3.png"))); // NOI18N
        getContentPane().add(enm, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, -20, -1, -1));

        enmAtk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spidership/SPR/webshot.png"))); // NOI18N
        enmAtk.setToolTipText("");
        getContentPane().add(enmAtk, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        projectile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spidership/SPR/TBomb.png"))); // NOI18N
        getContentPane().add(projectile, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, -1));

        enlifeBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spidership/SPR/lifebar.png"))); // NOI18N
        getContentPane().add(enlifeBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lifeBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spidership/SPR/lifebar.png"))); // NOI18N
        getContentPane().add(lifeBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 22, -1, -1));

        BG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spidership/SPR/basiscreen.png"))); // NOI18N
        getContentPane().add(BG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BGSpace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spidership/SPR/SPC.png"))); // NOI18N
        getContentPane().add(BGSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        if(Spidership.settings.gamestate){
        if(evt.getKeyCode() == KeyEvent.VK_W){
        Spidership.move.yspeed=-1*Spidership.settings.playershipspeed;
        }
        if(evt.getKeyCode() == KeyEvent.VK_S){
        Spidership.move.yspeed=+1*Spidership.settings.playershipspeed;
        }
        if(evt.getKeyCode() == KeyEvent.VK_A){
        Spidership.move.xspeed=-1*Spidership.settings.playershipspeed;
        }
        if(evt.getKeyCode() == KeyEvent.VK_D){
        Spidership.move.xspeed=+1*Spidership.settings.playershipspeed;
        }
        if(evt.getKeyCode() == KeyEvent.VK_G){
            Spidership.shoot.shooton = Spidership.shoot.shooton != true;
        }}
        //debugging
        if(evt.getKeyCode() == KeyEvent.VK_H && debugging){
        spidership.Spidership.dbt=new DebbuggingTool();
        spidership.Spidership.dbt.setVisible(true);
        }
       
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_W){
        Spidership.move.yspeed=0;
        }
        if(evt.getKeyCode() == KeyEvent.VK_S){
        Spidership.move.yspeed=0;

        }
        if(evt.getKeyCode() == KeyEvent.VK_A){
        Spidership.move.xspeed=0;

        }
        if(evt.getKeyCode() == KeyEvent.VK_D){
        Spidership.move.xspeed=0;

        }
    }//GEN-LAST:event_formKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel BG1;
    public static javax.swing.JLabel BGSpace;
    public static javax.swing.JLabel enlifeBar;
    public static javax.swing.JLabel enm;
    public static javax.swing.JLabel enmAtk;
    public static javax.swing.JLabel lifeBar;
    public static javax.swing.JLabel player;
    public static javax.swing.JLabel projectile;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
